# Generated by Django 3.0.2 on 2020-01-19 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, verbose_name=datetime.datetime(2020, 1, 19, 15, 35, 57, 792350))),
            ],
            options={
                'verbose_name_plural': 'Post',
            },
        ),
    ]
