# Generated by Django 3.0.2 on 2020-01-20 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='blog_post', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2020, 1, 20, 19, 23, 49, 411429)),
        ),
    ]
